{% set name = "pathtemplater" %}
{% set version = "1.0.0.dev3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "eefb054c6209daeef072260236c96b18dd8d5423d27508ae5c0e946b620b2a0c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pathtemplater

about:
  home: https://github.com/twlee79/pathtemplater
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL3
  license_file: 'LICENSE.md'
  summary: Package for templating paths, useful helper package for Snakemake
  description: "pathtemplater\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'twlee79'
