{% set name = "pathtemplater" %}
{% set version = "1.0.0.dev5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "6d01d8d33c984dfdca31e0b1a8cf2f28f57b3c78f5606fc38c4b5fbd8946070c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pathtemplater

about:
  home: https://github.com/twlee79/pathtemplater
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL3
  license_file: 'LICENSE.md'
  summary: Package for templating paths, useful helper package for Snakemake
  description: "pathtemplater\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'twlee79'
